# Generated by Django 3.2.16 on 2022-11-29 17:10

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(db_index=True, max_length=100)),
                ('full_name', models.CharField(db_index=True, max_length=100)),
                ('position', models.CharField(db_index=True, max_length=100)),
                ('emp_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=0, max_digits=7)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
